spring:
  datasource:
    url: jdbc:mysql://se-propify-ups-dev.cluster-cdzdurc22njb.us-east-1.rds.amazonaws.com:3306/shipping?useSSL=false
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: admin
    password: ZrPGedhYkxgiwfr3I1uh

    hikari:
      maximum-pool-size: 10